version: '3.8'

services:
  acompanhamento:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
    volumes:
      - ./app:/app/app  # Para desenvolvimento com hot reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Adicionar outros serviços conforme necessário (banco de dados, etc.)
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: acompanhamento
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
