"""criar tabela acompanhamento

Revision ID: 75b3c2ff2dfa
Revises: 
Create Date: 2025-07-26 14:21:19.651425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b3c2ff2dfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acompanhamento',
    sa.Column('id_acompanhamento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('cpf_cliente', sa.String(length=11), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('status_pagamento', sa.String(length=50), nullable=False),
    sa.Column('valor_pago', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tempo_estimado', sa.String(length=8), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_acompanhamento'),
    sa.UniqueConstraint('id_pedido')
    )
    op.create_table('item_pedido',
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(length=100), nullable=True),
    sa.Column('descricao_produto', sa.String(length=255), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('personalizacao', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['acompanhamento.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_produto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_pedido')
    op.drop_table('acompanhamento')
    # ### end Alembic commands ###
